/**
 * Web app manifest of the browser client, for "add to home screen" on phones (19 September 2026, user's wish: the Squorli
 * logo as the icon, and "Squorli - <server name>" offered as the name). The name depends on the server's settings, so the
 * manifest is a route (`/api/manifest.webmanifest`, under `/api` so the dev server's proxy reaches it too) and not a static
 * file. The icons are static files of the client (`apps/web/public/app-icons/`, generated by `tools/web-app-icons.mjs`).
 * iOS takes the icon from `apple-touch-icon` and the name from `apple-mobile-web-app-title` in the page (`apps/web`).
 */

/** Raise after regenerating the icons: the static files may be cached for a year (index.ts, `setHeaders`). Same value as in apps/web/index.html. */
export const APP_ICON_VERSION = 1;

/** Brand ground `--sq-bg` (docs/brand/AGENTS.md): splash screen and the system bars of the installed app. */
const BRAND_BG = "#0C1424";

export const webAppName = (serverName: string | null | undefined): string => {
  const name = serverName?.trim();
  return name ? `Squorli - ${name}` : "Squorli";
};

export function webAppManifest(serverName: string | null | undefined) {
  const icon = (file: string, size: number, purpose: "any" | "maskable") => ({ src: `/app-icons/${file}?v=${APP_ICON_VERSION}`, sizes: `${size}x${size}`, type: "image/png", purpose });
  return {
    name: webAppName(serverName),
    short_name: webAppName(serverName),
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: BRAND_BG,
    theme_color: BRAND_BG,
    icons: [icon("icon-192.png", 192, "any"), icon("icon-512.png", 512, "any"), icon("icon-maskable-512.png", 512, "maskable")],
  };
}
