#!/usr/bin/env node
/**
 * Emoji for the chat of the web client: font and data, generated into apps/web/src/emoji/ (`pnpm emoji`).
 *
 * Font: Noto Color Emoji (SIL Open Font License 1.1), self-hosted. Google Fonts cuts the font into slices with a
 * `unicode-range`, so a browser only fetches the slices whose emoji really occur. This tool downloads the slices Google
 * serves to Chromium (COLRv1 color glyphs, about 2 MB in total) once into apps/web/src/emoji/font/ together with the
 * license text, and writes font.css; from then on only our own server delivers them. Do NOT use the slices of the npm
 * package @fontsource/noto-color-emoji 5.3.1: they carry COLRv1 and SVG tables but render as blank boxes in Chromium
 * (checked with a headless Chrome on 17 September 2026; the package's unsliced file is fine but weighs 5.7 MB).
 * Safari has no COLRv1: styles.css only names the font under `@supports (font-tech(color-COLRv1))`, Safari keeps
 * Apple Color Emoji.
 *
 * Data: emojibase-data (MIT), names and keywords in German and English, shortcodes from the GitHub, iamcal (Slack/Discord
 * style) and emojibase sets. `shortcodes.ts` is loaded with the client (the Markdown parser needs it), `data.<locale>.ts`
 * only when the emoji picker opens.
 *
 * The output is committed, fonts included (the dev server and the Docker build need it, and neither has this tool or
 * should depend on Google at build time). Run it again for a newer font or after updating emojibase-data; needs internet
 * access for the font (`--no-font` regenerates the data only).
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const modules = join(root, "apps", "web", "node_modules");
const outDir = join(root, "apps", "web", "src", "emoji");
const json = (...p) => JSON.parse(readFileSync(join(modules, ...p), "utf8"));
const HEADER = "// GENERATED by tools/emoji.mjs, do not edit by hand. Data: emojibase-data (MIT, https://emojibase.dev).";

mkdirSync(outDir, { recursive: true });

// ---------- font ----------
const FONT_CSS_URL = "https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&display=swap";
const FONT_LICENSE_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/notocoloremoji/OFL.txt";
// Google Fonts answers by browser; this one gets the COLRv1 slices.
const CHROME = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

async function get(url, as) {
  const res = await fetch(url, { headers: { "user-agent": CHROME } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return as === "text" ? res.text() : Buffer.from(await res.arrayBuffer());
}

if (!process.argv.includes("--no-font")) {
  const fontDir = join(outDir, "font");
  try {
    const css = await get(FONT_CSS_URL, "text");
    const faces = [...css.matchAll(/src:\s*url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)\s*format\('woff2'\);\s*unicode-range:\s*([^;]+);/g)];
    if (faces.length === 0) throw new Error("keine woff2-Teile in der Antwort von Google Fonts gefunden");
    const version = /\/notocoloremoji\/(v\d+)\//.exec(faces[0][1])?.[1] ?? "unknown";
    const files = await Promise.all(faces.map((m) => get(m[1], "bytes")));
    const license = await get(FONT_LICENSE_URL, "text");
    rmSync(fontDir, { recursive: true, force: true });
    mkdirSync(fontDir, { recursive: true });
    files.forEach((bytes, i) => writeFileSync(join(fontDir, `noto-color-emoji-${i}.woff2`), bytes));
    writeFileSync(join(fontDir, "OFL.txt"), license.replace(/\r\n?/g, "\n"));
    writeFileSync(join(fontDir, "font.json"), JSON.stringify({ name: "Noto Color Emoji", version, license: "OFL-1.1", source: "https://github.com/googlefonts/noto-emoji", from: FONT_CSS_URL }, null, 2) + "\n");
    writeFileSync(join(outDir, "font.css"), [
      `/* GENERATED by tools/emoji.mjs, do not edit by hand. Noto Color Emoji ${version} (COLRv1 slices as served by Google Fonts), Copyright 2021 Google Inc., SIL Open Font License 1.1 (font/OFL.txt). */`,
      ...faces.map((m, i) => `@font-face { font-family: "Noto Color Emoji"; font-style: normal; font-weight: 400; font-display: swap; src: url("./font/noto-color-emoji-${i}.woff2") format("woff2"); unicode-range: ${m[2].trim()}; }`),
      "",
    ].join("\n"));
    console.log(`[emoji] Schrift ${version}: ${files.length} Teile, ${Math.round(files.reduce((n, b) => n + b.length, 0) / 1024)} kB`);
  } catch (e) {
    console.error(`[emoji] Schrift nicht geladen (${e.message}). Ohne Internet: node tools/emoji.mjs --no-font`);
    process.exit(1);
  }
}
if (!readdirSync(outDir).includes("font.css")) { console.error("[emoji] apps/web/src/emoji/font.css fehlt; einmal ohne --no-font ausführen"); process.exit(1); }

// ---------- data ----------
const dataPkg = json("emojibase-data", "package.json");
const sets = ["github", "iamcal", "emojibase"].map((n) => json("emojibase-data", "en", "shortcodes", `${n}.json`));
const codesOf = (hex) => [...new Set(sets.flatMap((s) => [s[hex] ?? []].flat()))];

/** One variant per skin tone (light .. dark); combinations of two different tones are left out. */
function skinsOf(e) {
  if (!e.skins) return null;
  const tones = ["1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"].map((tone) => e.skins.find((s) => {
    const used = s.hexcode.split("-").filter((h) => /^1F3F[B-F]$/.test(h));
    return used.length > 0 && used.every((h) => h === tone);
  })?.unicode);
  return tones.every(Boolean) ? tones : null;
}

const shortcodes = Object.create(null);
for (const locale of ["de", "en"]) {
  const list = json("emojibase-data", locale, "compact.json");
  const groups = json("emojibase-data", locale, "messages.json").groups.filter((g) => g.key !== "component");
  const out = groups.map((g) => ({
    key: g.key,
    emojis: list.filter((e) => e.group === g.order).sort((a, b) => a.order - b.order).map((e) => {
      const codes = codesOf(e.hexcode);
      if (locale === "en") for (const c of codes) shortcodes[c] ??= e.unicode;
      const skins = skinsOf(e);
      return [e.unicode, e.label, (e.tags ?? []).join(" ").toLowerCase(), codes.join(" "), ...(skins ? [skins] : [])];
    }),
  }));
  writeFileSync(join(outDir, `data.${locale}.ts`), [
    HEADER,
    `// emojibase-data ${dataPkg.version}, locale ${locale}: ${out.reduce((n, g) => n + g.emojis.length, 0)} emoji in ${out.length} groups. Loaded when the emoji picker opens.`,
    'import type { EmojiGroup } from "./types";',
    "",
    `export const GROUPS: EmojiGroup[] = JSON.parse(${JSON.stringify(JSON.stringify(out))});`,
    "",
  ].join("\n"));
}

writeFileSync(join(outDir, "shortcodes.ts"), [
  HEADER,
  `// emojibase-data ${dataPkg.version}: ${Object.keys(shortcodes).length} shortcodes (GitHub, iamcal, emojibase; the first set that knows a name wins).`,
  "",
  `export const SHORTCODES: Readonly<Record<string, string>> = JSON.parse(${JSON.stringify(JSON.stringify(shortcodes))});`,
  "",
].join("\n"));

console.log(`[emoji] ${Object.keys(shortcodes).length} Kurzcodes, Daten de/en geschrieben nach apps/web/src/emoji/`);
